# Generated by Django 4.1.5 on 2023-01-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='updated_at',
        ),
    ]
