# Generated by Django 4.1.5 on 2023-01-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_remove_measurement_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensor',
            new_name='SensorDetail',
        ),
    ]
