# Generated by Django 4.1.5 on 2023-01-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='measurement.sensordetail'),
            preserve_default=False,
        ),
    ]
